 export default {
     path:"/shopmanage",
     name:"shopMange",
     component:_=>import("@pages/shop-manage"),
     children:[
         {
             path:"businesslist",
             name:"business-list",
             component:_=>import("@pages/shop-manage/business-list"),
             meta:{
                breadcrumb:[
                    {
                        path:"/shopmanage",
                        text:"商家管理"
                    },
                    {
                        path:"/shopmanage/businesslist",
                        text:"商家列表" 
                    }
                ]
             }
         },
         {
            path:"businessmanage",
            name:"business-manage",
            component:_=>import("@pages/shop-manage/business-manage"),
            meta:{
               breadcrumb:[
                   {
                       path:"/shopmanage",
                       text:"商家管理"
                   },
                   {
                       path:"/shopmanage/businessmanage",
                       text:"商家管理" 
                   }
               ]
            }
        },
        {
            path:"orderlist",
            name:"order-list",
            component:_=>import("@pages/shop-manage/order-list"),
            meta:{
               breadcrumb:[
                   {
                       path:"/shopmanage",
                       text:"商家管理"
                   },
                   {
                       path:"/shopmanage/orderlist",
                       text:"订单列表" 
                   }
               ]
            }
        }
     ]   
 }